name: Mirror to GitLab

on:
  push:
    branches:
      - main  # Replace with your default branch name
  schedule:
    - cron: '0 * * * *'  # Runs every hour; adjust as needed

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensures the entire history is cloned

      - name: Mirror to GitLab
        run: |
          git remote add origin https://gitlab.com/learning4571813/Devops.git
          git push --mirror origin
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}

